import * as vscode from 'vscode';
import { SQLNotebookConnections } from './connections';
import { deleteConnectionConfiguration, editConnectionConfiguration } from './commands';
import { ParameterProvider } from './ParameterProvider'; // Asegura que busca en src
import { activateFormProvider } from './form';
import { SQLSerializer } from './serializer';
import { KernelManager } from './controller';
import { SqlCompletionItemProvider } from './completion';
import * as XLSX from 'xlsx';
import * as path from 'path';
import * as fs from 'fs';
import * as os from 'os';
import { format as formatSql } from 'sql-formatter';
import { embedImagesAsBase64 } from './embed-base64';
import { extractAttachmentsFromMarkdown } from './attachments-util';

export const notebookType = 'sql-notebook';
export const storageKey = 'sqlnotebook-connections';

function isAutoGeneratedPastedImageName(fileName: string): boolean {
  return /^(image(\s*\(\d+\)|[-_ ]\d+)?|pasted image(\s*\(\d+\)|[-_ ]\d+)?|screenshot(\s*\(\d+\)|[-_ ]\d+)?|captura(\s*\(\d+\)|[-_ ]\d+)?)\.(png|jpg|jpeg|gif|webp)$/i.test(fileName);
}

async function cleanupTemporaryEmbeddedFiles(files: string[]): Promise<void> {
  if (files.length === 0) {
    return;
  }

  await Promise.all(files.map(async (filePath) => {
    const fileName = path.basename(filePath);
    if (!isAutoGeneratedPastedImageName(fileName)) {
      return;
    }

    try {
      await fs.promises.unlink(filePath);
    } catch {
      // Ignore cleanup failures. Markdown already has embedded data URI.
    }
  }));
}

function getFullRange(doc: vscode.TextDocument): vscode.Range {
  if (doc.lineCount === 0) {
    return new vscode.Range(0, 0, 0, 0);
  }
  const lastLine = doc.lineCount - 1;
  const lastChar = doc.lineAt(lastLine).text.length;
  return new vscode.Range(0, 0, lastLine, lastChar);
}

function findNotebookForCellDocument(docUri: vscode.Uri): vscode.NotebookDocument | undefined {
  return vscode.workspace.notebookDocuments.find((notebook) =>
    notebook.notebookType === notebookType
      && notebook.getCells().some((cell) => cell.document.uri.toString() === docUri.toString())
  );
}

function findNotebookCellByDocument(docUri: vscode.Uri): { notebook: vscode.NotebookDocument; cell: vscode.NotebookCell; index: number } | undefined {
  for (const notebook of vscode.workspace.notebookDocuments) {
    if (notebook.notebookType !== notebookType) {
      continue;
    }
    const index = notebook.getCells().findIndex((cell) => cell.document.uri.toString() === docUri.toString());
    if (index >= 0) {
      return { notebook, cell: notebook.cellAt(index), index };
    }
  }
  return undefined;
}

function getCellAttachmentsFromMetadata(metadata: Record<string, any> | undefined): Record<string, Record<string, string>> {
  const attachments = metadata?.attachments;
  if (attachments && typeof attachments === 'object') {
    return attachments as Record<string, Record<string, string>>;
  }
  return {};
}

function generateUniqueAttachmentFilename(
  ext: string,
  existingAttachments: Record<string, Record<string, string>>
): string {
  let filename = `image.${ext}`;
  let counter = 1;
  while (existingAttachments[filename]) {
    filename = `image-${++counter}.${ext}`;
  }
  return filename;
}

class MarkdownImagePasteProvider implements vscode.DocumentPasteEditProvider {
  static readonly kind = vscode.DocumentDropOrPasteEditKind.Empty.append('markdown', 'image', 'attachment');
  static readonly PASTE_MIME_TYPES = ['image/png', 'image/jpeg', 'image/gif', 'image/webp', 'image/jpg'] as const;

  async provideDocumentPasteEdits(
    document: vscode.TextDocument,
    _ranges: readonly vscode.Range[],
    dataTransfer: vscode.DataTransfer,
    _context: vscode.DocumentPasteEditContext,
    token: vscode.CancellationToken
  ): Promise<vscode.DocumentPasteEdit[] | undefined> {
    const cellInfo = findNotebookCellByDocument(document.uri);
    if (!cellInfo) {
      return undefined;
    }

    // Read image bytes directly from clipboard — no file ever written to disk.
    let imageBytes: Uint8Array | undefined;
    let mimeType: string | undefined;
    for (const mime of MarkdownImagePasteProvider.PASTE_MIME_TYPES) {
      const item = dataTransfer.get(mime);
      if (item) {
        const file = item.asFile();
        if (file) {
          imageBytes = await file.data();
          mimeType = mime;
          break;
        }
      }
    }

    if (!imageBytes || !mimeType || token.isCancellationRequested) {
      return undefined;
    }

    // Normalise mime type and derive extension.
    const storageMime = mimeType === 'image/jpg' ? 'image/jpeg' : mimeType;
    const ext = storageMime === 'image/jpeg' ? 'jpg' : storageMime.split('/')[1];

    const existingAttachments = getCellAttachmentsFromMetadata(
      cellInfo.cell.metadata as Record<string, any> | undefined
    );
    const filename = generateUniqueAttachmentFilename(ext, existingAttachments);
    const base64 = Buffer.from(imageBytes).toString('base64');

    const newAttachments: Record<string, Record<string, string>> = {
      ...existingAttachments,
      [filename]: { [storageMime]: base64 }
    };

    const pasteEdit = new vscode.DocumentPasteEdit(
      `![${filename}](attachment:${filename})`,
      'Insert image as notebook attachment',
      MarkdownImagePasteProvider.kind
    );

    const additionalEdit = new vscode.WorkspaceEdit();
    additionalEdit.set(cellInfo.notebook.uri, [
      vscode.NotebookEdit.updateCellMetadata(cellInfo.index, {
        ...(cellInfo.cell.metadata ?? {}),
        attachments: newAttachments
      })
    ]);
    pasteEdit.additionalEdit = additionalEdit;

    return [pasteEdit];
  }
}

function getOpenTextDocument(docUri: vscode.Uri): vscode.TextDocument | undefined {
  return vscode.workspace.textDocuments.find((doc) => doc.uri.toString() === docUri.toString());
}

function hasEmbeddableMarkdownImage(markdown: string): boolean {
  const regex = /!\[[^\]]*\]\(([^)]+)\)/g;
  let match: RegExpExecArray | null;
  while ((match = regex.exec(markdown)) !== null) {
    const imagePath = match[1].trim();
    if (/^data:image\//i.test(imagePath)) {
      continue;
    }
    if (/^attachment:/i.test(imagePath)) {
      continue;
    }
    if (/^(https?:|vscode-|file:)/i.test(imagePath)) {
      continue;
    }
    return true;
  }
  return false;
}

const formatterLanguageByDriver: Record<string, string> = {
  mssql: 'tsql',
  mysql: 'mysql',
  postgres: 'postgresql',
  sqlite: 'sqlite',
  trino: 'trino'
};

export function activate(context: vscode.ExtensionContext) {
  context.subscriptions.push(
    vscode.workspace.registerNotebookSerializer(notebookType, new SQLSerializer())
  );

  const connectionsSidepanel = new SQLNotebookConnections(context);
  context.subscriptions.push(
    vscode.window.registerTreeDataProvider('sqlnotebook-connections', connectionsSidepanel)
  );

  vscode.commands.executeCommand('setContext', 'sqlnotebook.allCollapsed', false);

  context.subscriptions.push(
    vscode.commands.registerCommand('sqlnotebook.collapseAll', async () => {
      await vscode.commands.executeCommand('notebook.cell.collapseAllCellInputs');
      await vscode.commands.executeCommand('setContext', 'sqlnotebook.allCollapsed', true);
    })
  );

  context.subscriptions.push(
    vscode.commands.registerCommand('sqlnotebook.expandAll', async () => {
      await vscode.commands.executeCommand('notebook.cell.expandAllCellInputs');
      await vscode.commands.executeCommand('setContext', 'sqlnotebook.allCollapsed', false);
    })
  );

  const messaging = vscode.notebooks.createRendererMessaging('sqlnotebook-pro-interactive-renderer');
  context.subscriptions.push(
    messaging.onDidReceiveMessage(async ({ message }) => {
      if (message.type === 'export_data') {
        await handleExport(message.payload);
      }
    })
  );

  const parameterProvider = new ParameterProvider(context.extensionUri, context);
  context.subscriptions.push(
    vscode.window.registerWebviewViewProvider(ParameterProvider.viewType, parameterProvider)
  );

  context.subscriptions.push(
    vscode.commands.registerCommand('sqlnotebook.openParameters', () => {
      vscode.commands.executeCommand('sqlnotebook.parameters.focus');
    })
  );

  // Intelligent status sync: Mark as dirty and notify panel when cells are modified
  context.subscriptions.push(
    vscode.workspace.onDidChangeNotebookDocument(e => {
      if (e.notebook.notebookType === notebookType) {
        // Notify the webview to show UNSAVED
        (parameterProvider as any).updateWebviewState?.({ isDirty: true });
      }
    })
  );

  // Intelligent status sync: Refresh panel when switching between files
  context.subscriptions.push(
    vscode.window.onDidChangeActiveNotebookEditor(e => {
      (parameterProvider as any).refresh?.();
    })
  );

  context.subscriptions.push(
    vscode.workspace.onDidSaveNotebookDocument((n) => {
      if (n.notebookType === notebookType) {
        (parameterProvider as any).onExternalSave?.(n.uri.toString());
      }
    })
  );

  activateFormProvider(context);

  const kernelManager = new KernelManager(context, parameterProvider);
  context.subscriptions.push({ dispose: () => kernelManager.dispose() });

  const completionProvider = new SqlCompletionItemProvider(kernelManager, parameterProvider);
  context.subscriptions.push(
    vscode.languages.registerCompletionItemProvider('sql', completionProvider, '.', ' ', ',', '(', '\n')
  );

  context.subscriptions.push(
    vscode.commands.registerCommand('sqlnotebook.refreshKernels', () => {
      kernelManager.refresh();
    })
  );

  context.subscriptions.push(
    vscode.workspace.onDidChangeConfiguration(e => {
      if (e.affectsConfiguration('sqlnotebook.connections')) {
          kernelManager.refresh();
      }
    })
  );

  context.subscriptions.push(
    vscode.commands.registerCommand('sqlnotebook.exportToSQL', async () => {
      const notebook = vscode.window.activeNotebookEditor?.notebook;
      if (!notebook || notebook.notebookType !== notebookType) {
        return;
      }

      let output = '';
      const params = notebook.metadata?.custom?.parameters;
      if (params && typeof params === 'object' && Object.keys(params).length > 0) {
        output += `/*<SQL_PARAMS>\n${JSON.stringify(params, null, 2)}\n</SQL_PARAMS>*/\n\n`;
      }

      notebook.getCells().forEach((cell, i) => {
        if (i > 0) { output += '\n\n-- %%\n\n'; }
        if (cell.kind === vscode.NotebookCellKind.Markup) {
          output += `/*markdown\n${cell.document.getText()}\n*/`;
        } else {
          output += cell.document.getText();
        }
      });

      const uri = await vscode.window.showSaveDialog({
        defaultUri: notebook.uri.with({ path: notebook.uri.path.replace(/\.sql$/, '') + '_exported.sql' }),
        filters: { 'SQL files': ['sql'] },
        saveLabel: 'Export Legacy SQL'
      });

      if (uri) {
        await vscode.workspace.fs.writeFile(uri, new TextEncoder().encode(output));
        vscode.window.showInformationMessage(`Successfully exported to ${path.basename(uri.fsPath)}`);
      }
    })
  );

  // Intercept clipboard image paste before VS Code's default handler can write any file to disk.
  // Equivalent to how Jupyter handles image paste in notebook markdown cells.
  context.subscriptions.push(
    vscode.languages.registerDocumentPasteEditProvider(
      { language: 'markdown' },
      new MarkdownImagePasteProvider(),
      {
        providedPasteEditKinds: [MarkdownImagePasteProvider.kind],
        pasteMimeTypes: [...MarkdownImagePasteProvider.PASTE_MIME_TYPES]
      }
    )
  );

  // Fallback: embed local file paths (e.g. drag-dropped images) that already made it into the cell text.
  const markdownEmbedTimers = new Map<string, NodeJS.Timeout>();
  const markdownEmbedInProgress = new Set<string>();
  context.subscriptions.push(
    vscode.workspace.onDidChangeTextDocument(async (event) => {
      const doc = event.document;
      if (doc.languageId !== 'markdown') {
        return;
      }

      const docKey = doc.uri.toString();
      if (markdownEmbedInProgress.has(docKey)) {
        return;
      }

      if (!event.contentChanges.length) {
        return;
      }

      const original = doc.getText();
      if (!hasEmbeddableMarkdownImage(original)) {
        return;
      }

      const existingTimer = markdownEmbedTimers.get(docKey);
      if (existingTimer) {
        clearTimeout(existingTimer);
      }

      const timer = setTimeout(async () => {
        markdownEmbedTimers.delete(docKey);

        const currentDoc = getOpenTextDocument(doc.uri);
        if (!currentDoc || currentDoc.isClosed) {
          return;
        }

        const cellInfo = findNotebookCellByDocument(currentDoc.uri);
        if (!cellInfo || cellInfo.notebook.uri.scheme !== 'file') {
          return;
        }

        const currentText = currentDoc.getText();
        if (!hasEmbeddableMarkdownImage(currentText)) {
          return;
        }

        markdownEmbedInProgress.add(docKey);
        try {
          const notebookDir = path.dirname(cellInfo.notebook.uri.fsPath);
          const sourceVersion = currentDoc.version;
          const embedded = await embedImagesAsBase64(currentText, notebookDir);
          const extracted = extractAttachmentsFromMarkdown(embedded.markdown);
          if (Object.keys(extracted.attachments).length === 0) {
            return;
          }

          const latestDoc = getOpenTextDocument(currentDoc.uri);
          if (!latestDoc || latestDoc.isClosed) {
            return;
          }

          if (latestDoc.version !== sourceVersion) {
            return;
          }

          const latestCellInfo = findNotebookCellByDocument(latestDoc.uri);
          if (!latestCellInfo) {
            return;
          }

          const existingAttachments = getCellAttachmentsFromMetadata(latestCellInfo.cell.metadata as Record<string, any> | undefined);
          // Merge, renaming any collisions so existing attachments are never overwritten.
          const safeNewAttachments: Record<string, Record<string, string>> = {};
          for (const [key, value] of Object.entries(extracted.attachments)) {
            const ext = key.split('.').pop() ?? 'png';
            const base = key.replace(/\.[^.]+$/, '');
            let safeKey = key;
            let counter = 1;
            while (existingAttachments[safeKey] || safeNewAttachments[safeKey]) {
              safeKey = `${base}-${++counter}.${ext}`;
            }
            safeNewAttachments[safeKey] = value;
          }
          const mergedAttachments = { ...existingAttachments, ...safeNewAttachments };

          const edit = new vscode.WorkspaceEdit();
          edit.replace(latestDoc.uri, getFullRange(latestDoc), extracted.markdown);
          edit.set(latestCellInfo.notebook.uri, [
            vscode.NotebookEdit.updateCellMetadata(latestCellInfo.index, {
              ...(latestCellInfo.cell.metadata ?? {}),
              attachments: mergedAttachments
            })
          ]);
          try {
            const applied = await vscode.workspace.applyEdit(edit);
            if (applied) {
              await cleanupTemporaryEmbeddedFiles(embedded.embeddedFiles);
            }
          } catch (error: any) {
            if (!/Model is disposed/i.test(String(error?.message ?? error))) {
              console.error('Failed to embed markdown image', error);
            }
          }
        } finally {
          markdownEmbedInProgress.delete(docKey);
        }
      }, 250);

      markdownEmbedTimers.set(docKey, timer);
    })
  );

  context.subscriptions.push({
    dispose: () => {
      for (const timer of markdownEmbedTimers.values()) {
        clearTimeout(timer);
      }
      markdownEmbedTimers.clear();
    }
  });

  context.subscriptions.push(
    vscode.commands.registerCommand(
      'sqlnotebook.deleteConnectionConfiguration',
      deleteConnectionConfiguration(context, connectionsSidepanel)
    )
  );

  context.subscriptions.push(
    vscode.commands.registerCommand(
      'sqlnotebook.editConnection',
      editConnectionConfiguration(context)
    )
  );

  context.subscriptions.push(
    vscode.commands.registerCommand('sqlnotebook.refreshConnectionPanel', () => {
      connectionsSidepanel.refresh();
    })
  );

  context.subscriptions.push(
    vscode.commands.registerCommand(
      'sqlnotebook.expandCell',
      async (cell: vscode.NotebookCell) => {
        const editor = vscode.window.activeNotebookEditor;
        if (!editor || !cell) {
          return;
        }
        if (!editor || !cell) {
          return;
        }
        const range = new vscode.NotebookRange(cell.index, cell.index + 1);
        editor.selection = range;
        editor.revealRange(range);
        await new Promise(r => setTimeout(r, 0));
        await vscode.commands.executeCommand('notebook.cell.expandCellInput');
      }
    )
  );

  context.subscriptions.push(
    vscode.commands.registerCommand(
      'sqlnotebook.collapseCell',
      async (cell: vscode.NotebookCell) => {
        const editor = vscode.window.activeNotebookEditor;
        if (!editor || !cell) {
          return;
        }
        const range = new vscode.NotebookRange(cell.index, cell.index + 1);
        editor.selection = range;
        editor.revealRange(range);
        await new Promise(r => setTimeout(r, 0));
        await vscode.commands.executeCommand('notebook.cell.collapseCellInput');
      }
    )
  );

  context.subscriptions.push(
    vscode.commands.registerCommand('sqlnotebook.moveCellUp', async (cell: vscode.NotebookCell) => {
      if (cell) {
        const editor = vscode.window.activeNotebookEditor;
        if (editor) {
            const range = new vscode.NotebookRange(cell.index, cell.index + 1);
            editor.selection = range;
            editor.revealRange(range);
        }
      }
      await vscode.commands.executeCommand('notebook.cell.moveUp');
    })
  );

  context.subscriptions.push(
    vscode.commands.registerCommand('sqlnotebook.moveCellDown', async (cell: vscode.NotebookCell) => {
      if (cell) {
        const editor = vscode.window.activeNotebookEditor;
        if (editor) {
            const range = new vscode.NotebookRange(cell.index, cell.index + 1);
            editor.selection = range;
            editor.revealRange(range);
        }
      }
      await vscode.commands.executeCommand('notebook.cell.moveDown');
    })
  );

  context.subscriptions.push(
    vscode.commands.registerCommand('sqlnotebook.formatCell', async (cell: vscode.NotebookCell) => {
      if (!cell || cell.kind !== vscode.NotebookCellKind.Code) {
        return;
      }
      const doc = cell.document;
      const source = doc.getText();
      if (!source.trim()) {
        return;
      }

      const activeNotebook = vscode.window.activeNotebookEditor?.notebook;
      const driver = kernelManager.getDriverForNotebook(activeNotebook);
      const language = driver ? formatterLanguageByDriver[driver] : 'tsql';

      let formatted = source;
      try {
        formatted = formatSql(source, { language: language as any });
      } catch (e: any) {
        vscode.window.showErrorMessage(`SQL format failed: ${e?.message || e}`);
        return;
      }

      const lastLine = doc.lineCount > 0 ? doc.lineCount - 1 : 0;
      const lastChar = doc.lineCount > 0 ? doc.lineAt(lastLine).text.length : 0;
      const fullRange = new vscode.Range(0, 0, lastLine, lastChar);
      const edit = new vscode.WorkspaceEdit();
      edit.replace(doc.uri, fullRange, formatted);
      await vscode.workspace.applyEdit(edit);
    })
  );
}

async function handleExport({ data, columns, rows, format }: { data?: any[], columns?: any[], rows?: any[][], format: 'csv' | 'xlsx' }) {
  const hasMatrix = Array.isArray(columns) && Array.isArray(rows);
  if ((!data || data.length === 0) && (!hasMatrix || rows!.length === 0)) {
    vscode.window.showWarningMessage('No data to export.');
    return;
  }
  const now = new Date();
  const dateStr = now.toISOString().slice(0, 19).replace('T', '_').replace(/:/g, '-');
  const defaultFilename = `Results_${dateStr}.${format}`;

  let defaultUri: vscode.Uri;
  if (vscode.workspace.workspaceFolders && vscode.workspace.workspaceFolders.length > 0) {
      defaultUri = vscode.Uri.joinPath(vscode.workspace.workspaceFolders[0].uri, defaultFilename);
  } else {
      defaultUri = vscode.Uri.file(path.join(os.homedir(), 'Downloads', defaultFilename));
  }

  const filters: { [name: string]: string[] } = format === 'xlsx'
    ? { 'Excel files': ['xlsx'] }
    : { 'CSV files': ['csv'] };

  const uri = await vscode.window.showSaveDialog({
    saveLabel: 'Export',
    filters,
    defaultUri
  });

  if (!uri) {
    return;
  }

  try {
    const filePath = uri.fsPath;
    const ws = hasMatrix
      ? XLSX.utils.aoa_to_sheet([
          columns!.map(col => String(col ?? '')),
          ...rows!
        ])
      : XLSX.utils.json_to_sheet(data || []);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "Data");

    if (format === 'csv') {
      const csvContent = XLSX.utils.sheet_to_csv(ws);
      fs.writeFileSync(filePath, csvContent, 'utf8');
    } else {
      const buffer = XLSX.write(wb, { bookType: 'xlsx', type: 'buffer' });
      fs.writeFileSync(filePath, buffer);
    }

    const openAfterExport = vscode.workspace.getConfiguration('sqlnotebook').get('openAfterExport');

    if (openAfterExport) {
      await vscode.env.openExternal(vscode.Uri.file(filePath));
    } else {
      const openBtn = 'Open File';
      vscode.window.showInformationMessage(`Successfully exported to ${path.basename(filePath)}`, openBtn)
        .then(selection => {
          if (selection === openBtn) {
            vscode.env.openExternal(vscode.Uri.file(filePath));
          }
        });
    }

  } catch (err: any) {
    if (err.code === 'EBUSY' || err.message.includes('busy')) {
        vscode.window.showErrorMessage(`Export failed: The file "${path.basename(uri.fsPath)}" is open in Excel. Please close it and try again.`);
    } else {
        vscode.window.showErrorMessage(`Export failed: ${err.message}`);
    }
  }
}

export function deactivate() {}